pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Hello'
            }
        }
    }
    post {
        success {
            echo 'Completed'
        }
    }
}
