pipeline {
    agent {
        label 'server1'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Hello'
            }
        }
    }
    post {
        success {
            echo 'Completed'
        }
    }
}
